server:
  port: 8888
spring:
  application:
    name: new-feeling-admin
  datasource:
      url: jdbc:mysql://localhost:3306/spring-cloud-system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      hikari:
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath:mappers/*/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#oauth2 client配置
security:
  oauth2:
    client:
      client-id: spring-cloud-system
      client-secret: system
      grant-type: password
      access-token-uri: http://localhost:8762/oauth/token
      scope: all
    resource:
      token-info-uri: http://localhost:8762/oauth/check_token
      user-info-uri: http://localhost:8762/auth/currentUser

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://127.0.0.1:8848