server:
  port: 8762

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-system?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        ddl:
          auto: validate
        dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
  redis:
    host: localhost
    port: 6379
    database: 0
  application:
    name: new-feelings-auth
  cloud:
    nacos:
      server-addr: http://localhost:8848
      discovery:
        enabled: true

