server:
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - StripPrefix=2
      routes:
        - id: route-new-feeling-admin
          uri: lb://new-feeling-admin
          predicates:
            - Path=/api/admin/**